2023-02-06 10:37:07,347 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:37:07,396 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:37:13,183 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:37:13,184 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:37:20,147 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:37:20,149 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:37:28,645 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:37:28,646 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:37:36,187 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:37:36,188 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:37:46,770 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:37:46,771 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:38:19,129 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:38:19,131 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
2023-02-06 10:39:29,374 in _network_loop_retry
  Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-06 10:39:29,375 in error_handler
  Traceback (most recent call last):
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 600, in _network_loop_retry
      if not await action_cb():
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 327, in polling_action_cb
      raise exc
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_updater.py", line 312, in polling_action_cb
      updates = await self.bot.get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 524, in get_updates
      updates = await super().get_updates(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 334, in decorator
      result = await func(*args, **kwargs)  # skipcq: PYL-E1102
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
      await self._post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 422, in _post
      return await self._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
      return await super()._do_post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\_bot.py", line 453, in _do_post
      return await request.post(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 165, in post
      result = await self._request_wrapper(
    File "C:\Users\naufalyafisusanto\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
      raise Conflict(message)
  telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  
